-- Создание новой базы данных
CREATE DATABASE user_service;

-- Подключение к созданной базе данных
\c user_service

-- Задержка перед созданием схемы и таблиц
DO

$$
BEGIN
   FOR i IN 1..10 LOOP
      BEGIN
         PERFORM 1;
         EXIT;
      EXCEPTION WHEN others THEN
         RAISE NOTICE 'Waiting for database to become available...';
         PERFORM pg_sleep(1); -- Ждем 1 секунду
      END;
   END LOOP;
END

$$;

-- Установка текущей схемы
SET search_path = user_service_schema;

-- Создание новой схемы
CREATE SCHEMA IF NOT EXISTS user_service_schema;

-- Создание таблицы
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    name VARCHAR(100),
    surname VARCHAR(100),
    "dateOfBirth" DATE
);

-- Добавление тестовых данных
INSERT INTO users (email, password, name, surname, "dateOfBirth")
VALUES ('alice@example.com', 'password123', 'Alice', 'Smith', '1990-01-15'),
       ('bob@example.com', 'password456', 'Bob', 'Johnson', '1985-07-22'),
       ('charlie@example.com', 'password789', 'Charlie', 'Brown', '1978-03-11');